/**
 * Propositions de « streak » pour la semaine à venir, envoyées aux parents
 * dans le compte rendu hebdomadaire. Une par semaine d'année scolaire (1 à 36),
 * en rotation. {prenom} est remplacé par le prénom de l'élève.
 */
export const PROPOSITIONS_HEBDO: string[] = [
  "C'est la rentrée : proposez à {prenom} de lancer sa toute première streak — 5 jours d'automatismes d'affilée cette semaine, et la machine est lancée.",
  "Deuxième semaine : l'objectif est de tenir la streak d'automatismes ET d'ajouter la première dictée de l'année. Un duo gagnant.",
  "Proposez un mini-marathon : automatismes chaque jour d'école, et la série de problèmes du week-end pour finir en beauté.",
  "Une streak se construit en 21 jours, dit-on. {prenom} en est où ? Cette semaine, pas un jour sans ses 10 calculs.",
  "Défi famille : et si vous faisiez la dictée en même temps que {prenom} ? Le premier qui fait zéro faute choisit le dessert.",
  "Six semaines de classe : c'est le moment du premier examen bilan ! Proposez à {prenom} de le passer, ses révisions se programmeront automatiquement.",
  "Nouvelle idée : {prenom} invite un ami dans un groupe sur le site, et que le meilleur garde sa streak — l'émulation fait des merveilles.",
  "Cette semaine, cap sur la régularité : automatismes 5 jours sur 7, même 10 minutes, même fatigué. C'est la constance qui paie.",
  "Proposez à {prenom} de battre son record de streak d'automatismes. Un record personnel, ça se célèbre !",
  "Les vacances approchent peut-être : proposez de garder une mini-streak (3 automatismes dans la semaine) pour ne pas casser la dynamique.",
  "Semaine spéciale dictée : deux dictées au lieu d'une, et {prenom} verra son score s'améliorer d'une semaine à l'autre.",
  "Un problème de maths par jour pendant 4 jours : un mini-défi qui muscle le raisonnement plus que dix exercices mécaniques.",
  "Mi-trimestre : jetez un œil ensemble à la page Mes progrès, félicitez ce qui monte, et choisissez UN point à travailler cette semaine.",
  "Proposez un défi donnant-donnant : si {prenom} valide son défi de la semaine, vous validez la récompense sans négocier. Parole tenue des deux côtés.",
  "La streak de fondamentaux hebdo est souvent l'oubliée : cette semaine, elle passe en priorité numéro un.",
  "Nouveau bilan en vue ? Tous les 6 semaines, c'est le rythme idéal. Proposez-le à {prenom} ce week-end.",
  "Semaine de consolidation : refaire une activité ratée (moins de 70 %) pour la valider, c'est comme ça qu'on apprend vraiment.",
  "Défi de milieu d'année : la streak parfaite — automatismes, dictée, problèmes ET fondamentaux, tous validés cette semaine.",
  "Proposez à {prenom} de viser le Winner of the week de son groupe. Rien de tel qu'une compétition amicale pour se motiver.",
  "Janvier ou pas, c'est le bon moment pour une bonne résolution : une streak de 7 jours d'automatismes, à commencer lundi.",
  "Cette semaine, l'accent sur la dictée : réécouter, taper, corriger, comprendre les pièges. Dix minutes qui rapportent gros au brevet.",
  "Un chapitre terminé (examen à plus de 70 %) apparaît dans le fil du groupe de {prenom} — de quoi récolter quelques « Bien joué ! » mérités.",
  "Proposez de monter la barre du défi hebdo d'un cran (par exemple 6 automatismes au lieu de 5). Petit pas, grand effet.",
  "Semaine tremplin : un examen bilan pour mesurer le chemin parcouru depuis le dernier. Les progrès sont souvent invisibles au quotidien — là, ils se voient.",
  "La régularité bat le talent quand le talent n'est pas régulier. Cette semaine : pas un jour sans ouvrir le site, même cinq minutes.",
  "Proposez un échange de rôles : {prenom} vous fait passer la dictée de la semaine, et corrige VOS fautes avec les pièges expliqués.",
  "Objectif souvenir : une streak d'un mois complet d'automatismes. Si elle tombe cette semaine, ça se fête dignement.",
  "Les révisions programmées s'accumulent ? Cette semaine, on en coche deux — et la liste redevient respirable.",
  "Dernier trimestre en vue : proposez à {prenom} de refaire les examens des chapitres moyennement réussis. La deuxième fois est toujours la bonne.",
  "Semaine d'endurance : automatismes tous les jours, y compris le week-end. Une streak de 7/7, c'est la médaille d'or de la régularité.",
  "Le brevet ou le prochain contrôle approche : un brevet blanc ou un bilan cette semaine vaut mieux que trois soirées de relecture passive.",
  "Proposez un duel de streak dans le groupe : celui qui perd sa streak cette semaine prépare le petit-déjeuner de l'autre.",
  "Presque au bout de l'année : cette semaine, {prenom} choisit SON chapitre préféré et refait l'examen pour le plaisir du sans-faute.",
  "Semaine de révisions générales : un bilan par matière principale, et les points faibles se révisent tout seuls grâce aux révisions programmées.",
  "L'avant-dernière ligne droite : maintenir la streak jusqu'au bout de l'année, c'est le plus beau des trophées. Tenez bon ensemble.",
  "Dernière semaine : bravo pour l'année entière ! Une dernière dictée, un dernier défi — et de vraies vacances bien méritées.",
];
